server:
    session: 
       timeout: 1800
       cookie: 
         secure: true
    error:
       whitelabel:
         enabled: false
    environment-type: DEV
spring:
    profiles:
        active: dev,local_ping   
cjp:
  proxy:
    timeout: 10000
  serverUrl: https://tstservices.emirates.com/resconnect/cjp
  oauth2:
    client:
        grantType: client_credentials
        clientId: resconnectsit_cjp_client
        clientSecret: FqITzzpPF1TFG22OSfVtzV7YAGUriEOOX16Mn3rpSV5iK0ZSpvibzi457hFU0rV8
        accessTokenUri: https://ssostg.emirates.com/as/token.oauth2
        
session-couchbase:
  timeout-in-seconds: 1800
  persistent:
    namespace: testapplication
    couchbase:
      hosts: "lnxdevvm727"
      bucket-name: ssui_dev_bucket
      password: ssui_dev_bucket
    principal-sessions:
      enabled: false
  in-memory:
    enabled: false
cache-couchbase:
  cacheHosts: "lnxdevvm727"
  cacheBucketName: ssui_dev_bucket
  cacheBucketPassword: ssui_dev_bucket
jms-call-integration:
  server: tcp://hqlinuxdevbl105.hq.emirates.com:7225
  username: ssui_usr
  password: ssui_usr
  topic: SSUI.BT.EK.TMAIN
logging.level.com.github.mkopylec.sessioncouchbase: trace
ssui:
    wsrsConnectionTimeout: 10000
    wsrsReadTimeout: 60000
    hostingCity: DXB
    serverUrl: "http://localhost:8080/connect/res"
    disableCsrf: false
    enableConcurrentUsrChk: false
    concurrentUser: 5
    allowedCROSDomains: "http://localhost:9004"
    excludedCROSUrls: "/payment/processCPGPaymentResponseCallback,/sales/booking/processTPCallBack,/payment/processNBDPaymentResponseCallback,/gadsend_temp.html,/app/rest/account,/rewards/profile/getLicenseDocument"    
    emsAlertConfig:
      paymentReviewProcessLog: /apps/jboss/jboss-eap-6.4.0/paymentReviewProcessLog.txt
    notification:
       batchsize: 10
info:
    app:
      name: "Connect"
      version: "1.2.0"
file:
  limit:
    uploadperfile: 1500000
    maxupload: 4500000
